spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.1.11.176:3306/example_Vue?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: 1qaz@WSX
mybatis:
   mapperLocations: classpath:/mapper/*.xml
